# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=28, unique=True)),
                ('nodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Nodes')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
    ]
