# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20161018_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='label',
            field=models.CharField(max_length=28, unique=True),
        ),
    ]
