# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=28, unique=True)),
                ('secretkey', models.CharField(max_length=16)),
                ('subsperday', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('label',),
            },
        ),
    ]
