# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='subsperdayremain',
            field=models.IntegerField(default=0),
        ),
    ]
